version: '2'

services:
  haproxy:
    image: haproxy:1.7
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/localtime:/etc/localtime
      - /opt/ci-with-haproxy/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - /opt/ci-with-haproxy/haproxy/haproxy.pem:/haproxy.pem

  jenkins:
    # Build the jenkins image from the jenkins/ directory.
    # We need to do it because:
    #  (a) we need to add plugins to jenkins.
    #  (b) We need to fix the timezone in Dockerfile, which cannot be done at runtime.
    build: jenkins/
    ports: 
      - "50000:50000"
    volumes:
      - /etc/localtime:/etc/localtime
      - /opt/ci-with-haproxy/jenkins/jenkins_home:/var/jenkins_home 
    # The jenkins context is being handled in the jenkins/Dockerfile , so no need to duplicate it here.
    # command: --prefix=/jenkins

  artifactory:
    # Build artifactory image from the artifactory/ directory .
    # We need to do it because we need to fix the TimeZone, which can only be done in Dockerfile
    # build: artifactory/
    image: mattgruter/artifactory
    volumes:
      - /etc/localtime:/etc/localtime
      - /opt/ci-with-haproxy/artifactory/data:/artifactory/data 
      - /opt/ci-with-haproxy/artifactory/logs:/artifactory/logs 
      - /opt/ci-with-haproxy/artifactory/backup:/artifactory/backup
    environment:
      - JAVA_OPTS='-Djsse.enableSNIExtension=false'

